/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#6e2c00",
        "on-primary-fixed-variant": "#264191",
        "primary-container": "#1e3a8a",
        "background": "#f7f9fb",
        "outline": "#757682",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#773205",
        "surface-container": "#eceef0",
        "secondary": "#a53936",
        "on-tertiary-container": "#f39461",
        "on-surface-variant": "#444651",
        "primary-fixed-dim": "#b6c4ff",
        "outline-variant": "#c5c5d3",
        "tertiary-fixed": "#ffdbcb",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "on-tertiary-fixed": "#341100",
        "surface-container-lowest": "#ffffff",
        "surface": "#f7f9fb",
        "inverse-surface": "#2d3133",
        "tertiary-fixed-dim": "#ffb691",
        "status-success": "#10B981",
        "table-border": "#E2E8F0",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#410004",
        "text-main": "#1E293B",
        "status-danger": "#EF4444",
        "surface-tint": "#4059aa",
        "on-primary-container": "#90a8ff",
        "on-secondary-fixed-variant": "#852221",
        "surface-container-low": "#f2f4f6",
        "surface-bright": "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#00164e",
        "secondary-fixed": "#ffdad7",
        "surface-container-highest": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "status-warning": "#F59E0B",
        "on-surface": "#191c1e",
        "text-muted": "#64748B",
        "on-secondary-container": "#721315",
        "primary": "#00236f",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "tertiary": "#4b1c00",
        "secondary-container": "#fe7c74",
        "primary-fixed": "#dce1ff",
        "inverse-primary": "#b6c4ff",
        "secondary-fixed-dim": "#ffb3ad",
        "on-error": "#ffffff"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "section-margin": "40px",
        "stack-gap": "16px",
        "container-padding": "24px",
        "grid-gutter": "20px",
        "base-unit": "4px"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "label-nis": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "button-text": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "label-nis": ["16px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "button-text": ["16px", { lineHeight: "1", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}